name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
        pub = 'public key string you wish to decode' def addr_decode(pub, testnet=True): h3 = hashlib.sha256(unhexlify(pub)) h4 = hashlib.new('ripemd160', h3.digest()) result =(b'\x00' if not testnet else b'\x6f') + h4.digest() h5 = hashlib.sha256(result) h6 = hashlib.sha256(h5.digest()) result += h6.digest()[:4] return b58encode(result)
